{{- if .Values.persistence.enabled }}
{{- $redis := .Values.persistence.persistentVolumeClaim.redis -}}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "harbor.redis" . }}-pv
  annotations:
  {{- range $key, $value := $redis.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if eq .Values.persistence.resourcePolicy "keep" }}
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: redis
spec:
  storageClassName: {{ template "harbor.redis" . }}-volume
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: {{ .Values.nodeAffinityPreset.key}}
          operator: Exists
  capacity:
    storage: {{ $redis.size | quote }}
  accessModes: 
    - {{ $redis.accessMode }}
  local:
    path: {{ $redis.sharePath }}
{{- end }}
