apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slurm-jobdir-pvc
  namespace: {{ .Values.namespace.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.jobdir.size }}
  storageClassName: {{ .Values.storage.storageClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-storage-pvc
  namespace: {{ .Values.namespace.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.mysql.size }}
  storageClassName: {{ .Values.storage.storageClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jwt-pvc
  namespace: {{ .Values.namespace.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.jwt.size }}
  storageClassName: {{ .Values.storage.storageClassName }}
