apiVersion: v1
kind: Secret
metadata:
  name: slurm-credentials
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.mysqlRootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.secrets.mysqlDatabase | quote }}
  MYSQL_USER: {{ .Values.secrets.mysqlUser | quote }}
  MYSQL_PASSWORD: {{ .Values.secrets.mysqlPassword | quote }}
{{- if .Values.secrets.sshPublicKey }}
  SSH_PUBLIC_KEY: {{ .Values.secrets.sshPublicKey | quote }}
{{- end }}