apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: exchange-ingress
  namespace: default
spec:
  ingressClassName: traefik
  rules:
  - host: exchange.hostip.nip.io
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service: 
              name: data-exchange-service-cs-rw-service
              port:
                number: 8080
  - host: '*.exchange.hostip.nip.io'
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service: 
              name: data-exchange-service-cs-rw-service
              port:
                number: 8080