apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: harborportal 
  namespace: default    # 這裡要填 Kibana 所在 namespace
spec:
  ingressClassName: traefik
  rules:
  - host: harbor.hostip.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: harbor   # 注意 Service 名稱
            port:
              number: 80
              
