{{- if .Values.core.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}-core-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Values.app }}-core-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.app }}-core-deployment
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
      - name: {{ .Values.app }}-core
        image: {{ .Values.images.mts }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.service.core.http.port }}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/ASUS
        - name: log-volume
          mountPath: /var/log/ASUS
        - name: socket-volume
          mountPath: /run
        - name: assets-volume
          mountPath: /var/lib/ASUS/metering-service/assets/assets.fld
        readinessProbe:
          tcpSocket:
            port: {{ .Values.service.core.http.port }}
          initialDelaySeconds: 10
          periodSeconds: 15
      - name: debugger
        image: {{ .Values.images.debugger }}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/ASUS
        - name: socket-volume
          mountPath: /run
        - name: log-volume
          mountPath: /var/log/ASUS
        - name: assets-volume
          mountPath: /var/lib/ASUS/metering-service/assets/assets.fld
      {{- if .Values.images.filebeat }}
      - name: filebeat
        image: {{ .Values.images.filebeat }}
        command: ['filebeat', '-e', '-strict.perms=false', '--path.config', "/etc/filebeat"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: log-volume
          mountPath: /var/log/ASUS
        - name: filebeat-config
          mountPath: /etc/filebeat/filebeat.yml
          subPath: filebeat.yml
      {{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Values.app }}-config
      - name: log-volume
        emptyDir: {}
      - name: socket-volume
        emptyDir: {}
      - name: assets-volume
        configMap:
          name: {{ .Values.app }}-assets
      {{- if .Values.images.filebeat }}
      - name: filebeat-config
        configMap:
          name: {{ .Values.app }}-filebeat-config
      {{- end}}
      # imagePullSecrets:
      # - name: regcred
{{- end }}
