{{- if .Values.persistence.enabled }}
{{- $registry := .Values.persistence.persistentVolumeClaim.registry -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "harbor.registry" . }}-pvc
  annotations:
  {{- range $key, $value := $registry.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if eq .Values.persistence.resourcePolicy "keep" }}
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: registry
spec:
  storageClassName: {{ template "harbor.registry" . }}-volume
  accessModes: 
    - {{ $registry.accessMode }}
  resources:
    requests:
      storage: {{ $registry.size }}
{{- end }}
