app: container-registry-management-rw

core:
  enabled: false

proxy:
  enabled: true
  configmap:
    version: 0.1.3-42690f69
    kind: Proxy
    containerregistrymanagement:
      scopes:
        availability_district: "tw-tc-ad1"
    proxy:
      instance: ContainerRegistryManagement-RW-Proxy
      developer: true
      http:
        host: 0.0.0.0:8107
      logger:
        system_log:
          path: /var/log/ASUS
      mode: rw #supported: ro, rw
      scopes:
        # external_domain 主要提供外部存取 CRM Proxy 使用，也可以是 IP + Port 如 http://192.168.88.166:8107
        # 預設為：http://pegasus-cloud-crmserver:8107
        external_domain: https://crm.hostip.nip.io ####
        project_extra_key: "iservice.projectSysCode"
    image_registry:
      provider: harbor
      harbor:
        host: http://harbor.default.svc.cluster.local
        timeout_sec: 5
        username: admin
        password: password

jobScheduler:
  enabled: false

service:
  core:
    enableNodePort: false
  proxy:
    enableNodePort: false
