config_file: "config/trustedcloud.yaml"

service:
  enableNodePort: false

deployment:
  spec:

filebeat_enabled: true
elasticSearch:
  hosts: ["http://elasticsearch-es-http.default.svc.cluster.local:9200"]
  username: "elastic"
  password: "password"
