_format_version: "3.0"
plugins: 
- config:
    credentials: false
    exposed_headers: null
    headers: null
    max_age: null
    methods:
    - GET
    - HEAD
    - PUT
    - PATCH
    - POST
    - DELETE
    - OPTIONS
    - TRACE
    - CONNECT
    origins:
    - '*'
    preflight_continue: false
    private_network: false
  enabled: true ####################
  name: cors ########有前端網站使用 API 時開啟
  protocols:
  - grpc
  - grpcs
  - http
  - https
- config:
    add:
      body: []
      headers:
      - X-Namespace:public
      querystring: []
    append:
      body: []
      headers: []
      querystring: []
    http_method: null
    remove:
      body: []
      headers: []
      querystring: []
    rename:
      body: []
      headers: []
      querystring: []
    replace:
      body: []
      headers:
      - X-Namespace:public
      querystring: []
      uri: null
  enabled: true
  name: request-transformer ####
  protocols:
  - grpc
  - grpcs
  - http
  - https
- config:
    add:
      headers:
      - X-Namespace:public
      json: []
      json_types: []
    append:
      headers: []
      json: []
      json_types: []
    remove:
      headers: []
      json: []
    rename:
      headers: []
    replace:
      headers:
      - X-Namespace:public
      json: []
      json_types: []
  enabled: true 
  name: response-transformer 
  protocols:
  - grpc
  - grpcs
  - http
  - https
services:
- connect_timeout: 60000 ###iam
  enabled: true
  host: iam-service
  name: iam-service
  path: /
  port: 8084
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    methods:
    - GET
    - POST
    - DELETE
    - HEAD
    - OPTIONS
    - PUT
    - PATCH
    name: iam-auth
    path_handling: v1
    paths:
    - /iam/api/v1
    plugins:
    - config:
        enable_json_header: null
        enable_permission_validate: null
        enable_raw_header: true
        enable_url_encode: null
        hosts:
        - iam-service:5051
        redirect_types: null
        redirect_url: null
        token_key_in_cookie: null
        verified_service: null
      enabled: true
      name: kong-auth-plugin
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  - https_redirect_status_code: 426
    methods:
    - POST
    - OPTIONS
    name: iam-login
    path_handling: v1
    paths:
    - /iam/api/v1/login
    - /iam/api/v1/admin/login
    - /iam/api/v1/mfa/verify
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  - https_redirect_status_code: 426
    methods:
    - GET
    - OPTIONS
    name: iam-no-auth
    path_handling: v1
    paths:
    - /iam/api/v1/scopes
    - /iam/api/v1/version
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  - https_redirect_status_code: 426
    methods:
    - POST
    - GET
    - OPTIONS
    name: no-auth-saml
    path_handling: v1
    paths:
    - /saml
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  tags:
  - pegasus-system
  write_timeout: 60000 ###iam
- connect_timeout: 60000 ###VPS 
  enabled: true
  host: vps-service 
  name: vps-service
  path: /
  port: 8110
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    methods:
    - GET
    - POST
    - DELETE
    - HEAD
    - OPTIONS
    - PATHC
    - PUT
    name: vps-auth
    path_handling: v1
    paths:
    - /vps/api/v1
    plugins:
    - config:
        enable_json_header: null
        enable_permission_validate: null
        enable_raw_header: true
        enable_url_encode: null
        hosts:
        - iam-service:5051
        redirect_types: null
        redirect_url: null
        token_key_in_cookie: null
        verified_service: null
      enabled: true
      name: kong-auth-plugin
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  - https_redirect_status_code: 426
    methods:
    - GET
    - OPTIONS
    name: vps-no-auth
    path_handling: v1
    paths:
    - /vps/api/v1/version
    - /vps/api/v1/scopes
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  tags:
  - virtual-platform-service
  write_timeout: 60000  ###VPS
- connect_timeout: 60000
  enabled: true
  host: virtual-registry-management-core-service #vrm
  name: vrm-service
  path: /
  port: 8106
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    methods:
    - GET
    - POST
    - DELETE
    - PUT
    - PATCH
    - HEAD
    - OPTIONS
    name: vrm-auth
    path_handling: v1
    paths:
    - /vrm/api/v1
    plugins:
    - config:
        enable_json_header: null
        enable_permission_validate: null
        enable_raw_header: true
        enable_url_encode: null
        hosts:
        - iam-service:5051
        redirect_types: null
        redirect_url: null
        token_key_in_cookie: null
        verified_service: null
      enabled: true
      name: kong-auth-plugin
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  - https_redirect_status_code: 426
    methods:
    - GET
    - OPTIONS
    name: vrm-no-auth
    path_handling: v1
    paths:
    - /vrm/api/v1/version
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  tags:
  - virtual-registry-service
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: data-storage-service-public-service
  name: dss-public-service
  path: /
  port: 8080
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    methods:
    - GET
    - POST
    - DELETE
    - PATCH
    - PUT
    - HEAD
    - OPTIONS
    name: dss-public-auth
    path_handling: v1
    paths:
    - /dss-public/cs/api/v1
    plugins:
    - config:
        enable_json_header: null
        enable_permission_validate: null
        enable_raw_header: true
        enable_url_encode: null
        hosts:
        - iam-service:5051
        redirect_types: null
        redirect_url: null
        token_key_in_cookie: null
        verified_service: null
      enabled: true
      name: kong-auth-plugin
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  - https_redirect_status_code: 426
    methods:
    - GET
    - OPTIONS
    name: dss-public-no-auth
    path_handling: v1
    paths:
    - /dss-public/cs/api/v1/version
    - /dss-public/cs/api/v1/scopes
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  tags:
  - data-storage-service
  - public
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: app-playground-service-core-service
  name: aps-service
  path: /
  port: 8111
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    methods:
    - GET
    - POST
    - DELETE
    - PUT
    - PATCH
    - HEAD
    - OPTIONS
    name: aps-auth
    path_handling: v1
    paths:
    - /aps/api/v1
    plugins:
    - config:
        enable_json_header: null
        enable_permission_validate: null
        enable_raw_header: true
        enable_url_encode: null
        hosts:
        - iam-service:5051
        redirect_types: null
        redirect_url: null
        token_key_in_cookie: null
        verified_service: null
      enabled: true
      name: kong-auth-plugin
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  - https_redirect_status_code: 426
    methods:
    - GET
    - OPTIONS
    name: aps-no-auth
    path_handling: v1
    paths:
    - /aps/api/v1/version
    - /aps/api/v1/scopes
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  tags:
  - app-playground-service-core-service
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: site-storage-service-service
  name: sss-service
  path: /
  port: 8080
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    methods:
    - GET
    - POST
    - DELETE
    - PUT
    - PATCH
    - HEAD
    - OPTIONS
    name: sss-auth
    path_handling: v1
    paths:
    - /sss/cs/api/v1
    plugins:
    - config:
        enable_json_header: null
        enable_permission_validate: null
        enable_raw_header: true
        enable_url_encode: null
        hosts:
        - iam-service:5051
        redirect_types: null
        redirect_url: null
        token_key_in_cookie: null
        verified_service: null
      enabled: true
      name: kong-auth-plugin
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  - https_redirect_status_code: 426
    methods:
    - GET
    - OPTIONS
    name: sss-no-auth
    path_handling: v1
    paths:
    - /sss/cs/api/v1/version
    - /sss/cs/api/v1/scopes
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  tags:
  - site-storage-service
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: audit-track-service-core-service
  name: ats-service
  path: /
  port: 8115
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    methods:
    - GET
    - POST
    - DELETE
    - PUT
    - PATCH
    - HEAD
    - OPTIONS
    name: ats-auth
    path_handling: v1
    paths:
    - /ats/api/v1
    plugins:
    - config:
        enable_json_header: null
        enable_permission_validate: null
        enable_raw_header: true
        enable_url_encode: null
        hosts:
        - iam-service:5051
        redirect_types: null
        redirect_url: null
        token_key_in_cookie: null
        verified_service: null
      enabled: true
      name: kong-auth-plugin
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  - https_redirect_status_code: 426
    methods:
    - GET
    - OPTIONS
    name: ats-no-auth
    path_handling: v1
    paths:
    - /ats/api/v1/version
    - /ats/api/v1/scopes
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  tags:
  - audit-track-service-core-service
  write_timeout: 60000

- connect_timeout: 60000
  enabled: true
  host: data-exchange-service-fs-rw-service 
  name: des-rw-service
  path: /
  port: 8080
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    methods:
    - GET
    - POST
    - DELETE
    - PUT
    - PATCH
    - HEAD
    - OPTIONS
    name: des-rw-auth
    path_handling: v1
    paths:
    - /des/cs/api/v1
    plugins:
    - config:
        enable_json_header: null
        enable_permission_validate: null
        enable_raw_header: true
        enable_url_encode: null
        hosts:
        - iam-service:5051
        redirect_types: null
        redirect_url: null
        token_key_in_cookie: null
        verified_service: null
      enabled: true
      name: kong-auth-plugin
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  - https_redirect_status_code: 426
    methods:
    - GET
    - OPTIONS
    name: des-rw-no-auth
    path_handling: v1
    paths:
    - /des/cs/api/v1/version
    - /des/cs/api/v1/scopes
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  tags:
  - data-exchange-service-fs-rw-service 
  write_timeout: 60000
  